config/routes.rb
Rails.application.routes.draw do
  match '/search' => 'search#search', via: [ :get, :post ], as: :search
  root to: 'search#search'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :fetch_results

  def search
  end

  protected

    def fetch_results
      return unless request.post?
      begin
        now = Time.now.to_f
        @results  = Zillow::Api::Client.get_search_results params.slice(:address, :citystatezip)
        @results  = [ @results ] unless @results.is_a?(Array)
        @duration = ( Time.now.to_f - now ).round(2)
      rescue Zillow::Api::Exception::ZillowError => e
        @exception = e
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title Zillow Property Search
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    #container
      section#header
        h1 Zillow Property Search
      = yield
    = javascript_include_tag 'application', 'data-turbolinks-track' => true

app/views/search/_form.html.slim
section#search-form
  = form_tag search_path, method: :post, html: { id: 'search-form' } do
    .col6= text_field_tag :address, params[:address], placeholder: 'Address'
    .col4= text_field_tag :citystatezip, params[:citystatezip], placeholder: 'City/State or ZIP Code'
    .col12= submit_tag 'Search'

app/views/search/_search_result.html.slim
section.result
  .tiny
    .pull-right.muted Zillow ID ##{result['zpid']}
    => link_to "#{icon :'location-arrow'} Map This!".html_safe, result['links']['mapthishome']
    span.muted —
    => link_to "#{icon :flask} Comparable to...".html_safe, result['links']['comparables']
  h3= link_to result['address']['street'], result['links']['homedetails']
  = render 'zestimate', zestimate: result['zestimate']

app/views/search/_zestimate.html.slim
.col2.muted
  h4.thin Zestimate®
.col3
  h3 $#{number_to_human zestimate['amount']}
.col5
  h4.thin[class="#{zestimate['valueChange'].to_i > 0 ? 'green' : 'red'}"]
    - if zestimate['valueChange'].to_i > 0
      = icon :'angle-up'
    - else
      = icon :'angle-down'
    =< number_to_currency zestimate['valueChange'].to_i.abs
.clearfix
.tiny.muted Last updated #{time_ago_in_words(Date.strptime(zestimate['last_updated'], "%m/%d/%Y")) rescue zestimate['last_updated']} ago

app/views/search/search.html.slim
= render 'form'

- if defined?(@results)
  section.muted.center Zillow found #{pluralize @results.count, 'result'} in about #{@duration}s
  br
  #search-results
    - @results.each do |result|
      = render 'search_result', result: result

- elsif defined?(@exception)
  section.center
    h2 D'oh!
    h2.muted.thin= @exception.message